<?php
// includes/paises.php
// Lista de países con códigos y banderas basada en estándares ISO

$countries = [
    'AD' => ['name' => 'Andorra', 'flag' => 'ad'],
    'AE' => ['name' => 'Emiratos Árabes Unidos', 'flag' => 'ae'],
    'AF' => ['name' => 'Afganistán', 'flag' => 'af'],
    'AG' => ['name' => 'Antigua y Barbuda', 'flag' => 'ag'],
    'AI' => ['name' => 'Anguila', 'flag' => 'ai'],
    'AL' => ['name' => 'Albania', 'flag' => 'al'],
    'AM' => ['name' => 'Armenia', 'flag' => 'am'],
    'AO' => ['name' => 'Angola', 'flag' => 'ao'],
    'AQ' => ['name' => 'Antártida', 'flag' => 'aq'],
    'AR' => ['name' => 'Argentina', 'flag' => 'ar'],
    'AS' => ['name' => 'Samoa Americana', 'flag' => 'as'],
    'AT' => ['name' => 'Austria', 'flag' => 'at'],
    'AU' => ['name' => 'Australia', 'flag' => 'au'],
    'AW' => ['name' => 'Aruba', 'flag' => 'aw'],
    'AZ' => ['name' => 'Azerbaiyán', 'flag' => 'az'],
    'BA' => ['name' => 'Bosnia y Herzegovina', 'flag' => 'ba'],
    'BB' => ['name' => 'Barbados', 'flag' => 'bb'],
    'BD' => ['name' => 'Bangladesh', 'flag' => 'bd'],
    'BE' => ['name' => 'Bélgica', 'flag' => 'be'],
    'BF' => ['name' => 'Burkina Faso', 'flag' => 'bf'],
    'BG' => ['name' => '3Bulgaria', 'flag' => 'bg'],
    'BH' => ['name' => 'Bahréin', 'flag' => 'bh'],
    'BI' => ['name' => 'Burundi', 'flag' => 'bi'],
    'BJ' => ['name' => 'Benín', 'flag' => 'bj'],
    'BM' => ['name' => 'Bermudas', 'flag' => 'bm'],
    'BN' => ['name' => 'Brunéi', 'flag' => 'bn'],
    'BO' => ['name' => 'Bolivia', 'flag' => 'bo'],
    'BR' => ['name' => 'Brasil', 'flag' => 'br'],
    'BS' => ['name' => 'Bahamas', 'flag' => 'bs'],
    'BT' => ['name' => 'Bután', 'flag' => 'bt'],
    'BW' => ['name' => 'Botsuana', 'flag' => 'bw'],
    'BY' => ['name' => 'Bielorrusia', 'flag' => 'by'],
    'BZ' => ['name' => 'Belice', 'flag' => 'bz'],
    'CA' => ['name' => 'Canadá', 'flag' => 'ca'],
    'CD' => ['name' => 'República Democrática del Congo', 'flag' => 'cd'],
    'CF' => ['name' => 'República Centroafricana', 'flag' => 'cf'],
    'CG' => ['name' => 'Congo', 'flag' => 'cg'],
    'CH' => ['name' => 'Suiza', 'flag' => 'ch'],
    'CI' => ['name' => 'Costa de Marfil', 'flag' => 'ci'],
    'CL' => ['name' => 'Chile', 'flag' => 'cl'],
    'CM' => ['name' => 'Camerún', 'flag' => 'cm'],
    'CN' => ['name' => 'China', 'flag' => 'cn'],
    'CO' => ['name' => 'Colombia', 'flag' => 'co'],
    'CR' => ['name' => 'Costa Rica', 'flag' => 'cr'],
    'CU' => ['name' => 'Cuba', 'flag' => 'cu'],
    'CV' => ['name' => 'Cabo Verde', 'flag' => 'cv'],
    'CY' => ['name' => 'Chipre', 'flag' => 'cy'],
    'CZ' => ['name' => 'República Checa', 'flag' => 'cz'],
    'DE' => ['name' => 'Alemania', 'flag' => 'de'],
    'DJ' => ['name' => 'Yibuti', 'flag' => 'dj'],
    'DK' => ['name' => 'Dinamarca', 'flag' => 'dk'],
    'DM' => ['name' => 'Dominica', 'flag' => 'dm'],
    'DO' => ['name' => 'República Dominicana', 'flag' => 'do'],
    'DZ' => ['name' => 'Argelia', 'flag' => 'dz'],
    'EC' => ['name' => 'Ecuador', 'flag' => 'ec'],
    'EE' => ['name' => 'Estonia', 'flag' => 'ee'],
    'EG' => ['name' => 'Egipto', 'flag' => 'eg'],
    'ER' => ['name' => 'Eritrea', 'flag' => 'er'],
    'ES' => ['name' => 'España', 'flag' => 'es'],
    'ET' => ['name' => 'Etiopía', 'flag' => 'et'],
    'FI' => ['name' => 'Finlandia', 'flag' => 'fi'],
    'FJ' => ['name' => 'Fiyi', 'flag' => 'fj'],
    'FM' => ['name' => 'Micronesia', 'flag' => 'fm'],
    'FR' => ['name' => 'Francia', 'flag' => 'fr'],
    'GA' => ['name' => 'Gabón', 'flag' => 'ga'],
    'GB' => ['name' => 'Reino Unido', 'flag' => 'gb'],
    'GD' => ['name' => 'Granada', 'flag' => 'gd'],
    'GE' => ['name' => 'Georgia', 'flag' => 'ge'],
    'GH' => ['name' => 'Ghana', 'flag' => 'gh'],
    'GM' => ['name' => 'Gambia', 'flag' => 'gm'],
    'GN' => ['name' => 'Guinea', 'flag' => 'gn'],
    'GQ' => ['name' => 'Guinea Ecuatorial', 'flag' => 'gq'],
    'GR' => ['name' => 'Grecia', 'flag' => 'gr'],
    'GT' => ['name' => 'Guatemala', 'flag' => 'gt'],
    'GW' => ['name' => 'Guinea-Bisáu', 'flag' => 'gw'],
    'GY' => ['name' => 'Guyana', 'flag' => 'gy'],
    'HN' => ['name' => 'Honduras', 'flag' => 'hn'],
    'HR' => ['name' => 'Croacia', 'flag' => 'hr'],
    'HT' => ['name' => 'Haití', 'flag' => 'ht'],
    'HU' => ['name' => 'Hungría', 'flag' => 'hu'],
    'ID' => ['name' => 'Indonesia', 'flag' => 'id'],
    'IE' => ['name' => 'Irlanda', 'flag' => 'ie'],
    'IL' => ['name' => 'Israel', 'flag' => 'il'],
    'IN' => ['name' => 'India', 'flag' => 'in'],
    'IQ' => ['name' => 'Irak', 'flag' => 'iq'],
    'IR' => ['name' => 'Irán', 'flag' => 'ir'],
    'IS' => ['name' => 'Islandia', 'flag' => 'is'],
    'IT' => ['name' => 'Italia', 'flag' => 'it'],
    'JM' => ['name' => 'Jamaica', 'flag' => 'jm'],
    'JO' => ['name' => 'Jordania', 'flag' => 'jo'],
    'JP' => ['name' => 'Japón', 'flag' => 'jp'],
    'KE' => ['name' => 'Kenia', 'flag' => 'ke'],
    'KG' => ['name' => 'Kirguistán', 'flag' => 'kg'],
    'KH' => ['name' => 'Camboya', 'flag' => 'kh'],
    'KI' => ['name' => 'Kiribati', 'flag' => 'ki'],
    'KM' => ['name' => 'Comoras', 'flag' => 'km'],
    'KN' => ['name' => 'San Cristóbal y Nieves', 'flag' => 'kn'],
    'KP' => ['name' => 'Corea del Norte', 'flag' => 'kp'],
    'KR' => ['name' => 'Corea del Sur', 'flag' => 'kr'],
    'KW' => ['name' => 'Kuwait', 'flag' => 'kw'],
    'KZ' => ['name' => 'Kazajistán', 'flag' => 'kz'],
    'LA' => ['name' => 'Laos', 'flag' => 'la'],
    'LB' => ['name' => 'Líbano', 'flag' => 'lb'],
    'LC' => ['name' => 'Santa Lucía', 'flag' => 'lc'],
    'LI' => ['name' => 'Liechtenstein', 'flag' => 'li'],
    'LK' => ['name' => 'Sri Lanka', 'flag' => 'lk'],
    'LR' => ['name' => 'Liberia', 'flag' => 'lr'],
    'LS' => ['name' => 'Lesoto', 'flag' => 'ls'],
    'LT' => ['name' => 'Lituania', 'flag' => 'lt'],
    'LU' => ['name' => 'Luxemburgo', 'flag' => 'lu'],
    'LV' => ['name' => 'Letonia', 'flag' => 'lv'],
    'LY' => ['name' => 'Libia', 'flag' => 'ly'],
    'MA' => ['name' => 'Marruecos', 'flag' => 'ma'],
    'MC' => ['name' => 'Mónaco', 'flag' => 'mc'],
    'MD' => ['name' => 'Moldavia', 'flag' => 'md'],
    'ME' => ['name' => 'Montenegro', 'flag' => 'me'],
    'MG' => ['name' => 'Madagascar', 'flag' => 'mg'],
    'MH' => ['name' => 'Islas Marshall', 'flag' => 'mh'],
    'MK' => ['name' => 'Macedonia del Norte', 'flag' => 'mk'],
    'ML' => ['name' => 'Malí', 'flag' => 'ml'],
    'MM' => ['name' => 'Myanmar', 'flag' => 'mm'],
    'MN' => ['name' => 'Mongolia', 'flag' => 'mn'],
    'MR' => ['name' => 'Mauritania', 'flag' => 'mr'],
    'MT' => ['name' => 'Malta', 'flag' => 'mt'],
    'MU' => ['name' => 'Mauricio', 'flag' => 'mu'],
    'MV' => ['name' => 'Maldivas', 'flag' => 'mv'],
    'MW' => ['name' => 'Malaui', 'flag' => 'mw'],
    'MX' => ['name' => 'México', 'flag' => 'mx'],
    'MY' => ['name' => 'Malasia', 'flag' => 'my'],
    'MZ' => ['name' => 'Mozambique', 'flag' => 'mz'],
    'NA' => ['name' => 'Namibia', 'flag' => 'na'],
    'NE' => ['name' => 'Níger', 'flag' => 'ne'],
    'NG' => ['name' => 'Nigeria', 'flag' => 'ng'],
    'NI' => ['name' => 'Nicaragua', 'flag' => 'ni'],
    'NL' => ['name' => 'Países Bajos', 'flag' => 'nl'],
    'NO' => ['name' => 'Noruega', 'flag' => 'no'],
    'NP' => ['name' => 'Nepal', 'flag' => 'np'],
    'NR' => ['name' => 'Nauru', 'flag' => 'nr'],
    'NZ' => ['name' => 'Nueva Zelanda', 'flag' => 'nz'],
    'OM' => ['name' => 'Omán', 'flag' => 'om'],
    'PA' => ['name' => 'Panamá', 'flag' => 'pa'],
    'PE' => ['name' => 'Perú', 'flag' => 'pe'],
    'PG' => ['name' => 'Papúa Nueva Guinea', 'flag' => 'pg'],
    'PH' => ['name' => 'Filipinas', 'flag' => 'ph'],
    'PK' => ['name' => 'Pakistán', 'flag' => 'pk'],
    'PL' => ['name' => 'Polonia', 'flag' => 'pl'],
    'PS' => ['name' => 'Palestina', 'flag' => 'ps'],
    'PT' => ['name' => 'Portugal', 'flag' => 'pt'],
    'PW' => ['name' => 'Palaos', 'flag' => 'pw'],
    'PY' => ['name' => 'Paraguay', 'flag' => 'py'],
    'QA' => ['name' => 'Catar', 'flag' => 'qa'],
    'RO' => ['name' => 'Rumania', 'flag' => 'ro'],
    'RS' => ['name' => 'Serbia', 'flag' => 'rs'],
    'RU' => ['name' => 'Rusia', 'flag' => 'ru'],
    'RW' => ['name' => 'Ruanda', 'flag' => 'rw'],
    'SA' => ['name' => 'Arabia Saudí', 'flag' => 'sa'],
    'SB' => ['name' => 'Islas Salomón', 'flag' => 'sb'],
    'SC' => ['name' => 'Seychelles', 'flag' => 'sc'],
    'SD' => ['name' => 'Sudán', 'flag' => 'sd'],
    'SE' => ['name' => 'Suecia', 'flag' => 'se'],
    'SG' => ['name' => 'Singapur', 'flag' => 'sg'],
    'SI' => ['name' => 'Eslovenia', 'flag' => 'si'],
    'SK' => ['name' => 'Eslovaquia', 'flag' => 'sk'],
    'SL' => ['name' => 'Sierra Leona', 'flag' => 'sl'],
    'SM' => ['name' => 'San Marino', 'flag' => 'sm'],
    'SN' => ['name' => 'Senegal', 'flag' => 'sn'],
    'SO' => ['name' => 'Somalia', 'flag' => 'so'],
    'SR' => ['name' => 'Surinam', 'flag' => 'sr'],
    'SS' => ['name' => 'Sudán del Sur', 'flag' => 'ss'],
    'ST' => ['name' => 'Santo Tomé y Príncipe', 'flag' => 'st'],
    'SV' => ['name' => 'El Salvador', 'flag' => 'sv'],
    'SY' => ['name' => 'Siria', 'flag' => 'sy'],
    'SZ' => ['name' => 'Suazilandia', 'flag' => 'sz'],
    'TD' => ['name' => 'Chad', 'flag' => 'td'],
    'TG' => ['name' => 'Togo', 'flag' => 'tg'],
    'TH' => ['name' => 'Tailandia', 'flag' => 'th'],
    'TJ' => ['name' => 'Tayikistán', 'flag' => 'tj'],
    'TL' => ['name' => 'Timor Oriental', 'flag' => 'tl'],
    'TM' => ['name' => 'Turkmenistán', 'flag' => 'tm'],
    'TN' => ['name' => 'Túnez', 'flag' => 'tn'],
    'TO' => ['name' => 'Tonga', 'flag' => 'to'],
    'TR' => ['name' => 'Turquía', 'flag' => 'tr'],
    'TT' => ['name' => 'Trinidad y Tobago', 'flag' => 'tt'],
    'TV' => ['name' => 'Tuvalu', 'flag' => 'tv'],
    'TW' => ['name' => 'Taiwán', 'flag' => 'tw'],
    'TZ' => ['name' => 'Tanzania', 'flag' => 'tz'],
    'UA' => ['name' => 'Ucrania', 'flag' => 'ua'],
    'UG' => ['name' => 'Uganda', 'flag' => 'ug'],
    'US' => ['name' => 'Estados Unidos', 'flag' => 'us'],
    'UY' => ['name' => 'Uruguay', 'flag' => 'uy'],
    'UZ' => ['name' => 'Uzbekistán', 'flag' => 'uz'],
    'VA' => ['name' => 'Vaticano', 'flag' => 'va'],
    'VC' => ['name' => 'San Vicente y las Granadinas', 'flag' => 'vc'],
    'VE' => ['name' => 'Venezuela', 'flag' => 've'],
    'VN' => ['name' => 'Vietnam', 'flag' => 'vn'],
    'VU' => ['name' => 'Vanuatu', 'flag' => 'vu'],
    'WS' => ['name' => 'Samoa', 'flag' => 'ws'],
    'YE' => ['name' => 'Yemen', 'flag' => 'ye'],
    'ZA' => ['name' => 'Sudáfrica', 'flag' => 'za'],
    'ZM' => ['name' => 'Zambia', 'flag' => 'zm'],
    'ZW' => ['name' => 'Zimbabue', 'flag' => 'zw']
];
?>